name: format

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar las herramientas de formato
        run: pip install black==24.1.0 ruff==0.1.14

      - name: black
        run: black --config .black --check --diff .

      - name: ruff
        run: ruff check .
